### ISSUE TITLE
Unhandled exception when making a new KCL

### ISSUE THREAD

**Issue by bavario-lginc** [SuperHackio/NeoKCLCreate#1]
Yesterday, I had some trouble with `wkclt` being not accurate and glitching out the collision of my Mario Galaxy 2 level. So, I wanted to try and use NeoKCLCreate and see if it had the same issues.

I tried it with two models, one of them being the visual model of the PeachCastlePlanet object converted to .obj. This one loaded correctly upon pressing the "New" button, but once I tried saving the new kcl, I got an error that my model had too many normals (as expected from a visual model).

The second model I tested it with was simply the Collision file used in the vanilla game for PeachCastlePlanet, again. But upon selecting it, I got the following error. Pressing Continue does nothing.
![grafik](https://user-images.githubusercontent.com/35093969/167289799-8a9bddb7-e8fb-42ce-84bb-995d14b4777e.png)
Since this is German, I'll do my best to translate it for you:
```
Unhandled exception in the application. Press "Continue" to ignore the error and continue the execution of the application. Press "Exit" to close the application instantly.

The input string has the wrong format.
```

Here is the .obj file in zip format for you to try it:
[PeachCastlePlanet.zip](https://github.com/SuperHackio/NeoKCLCreate/files/8646741/PeachCastlePlanet.zip)

Let me know if you need any further debugging information.

**Comment by SuperHackio** [comment]
I have found the problem.

It's actually no issue with NeoKCLCreate, rather, an issue with Hack.io.KCL. This issue has been fixed successfully.
